apiVersion: v1
kind: Service
metadata: 
    name: k8s-districtpdsmanagement-service
spec:
    selector:
        app: k8s-districtpdsmanagement
    ports:
        - port: 8282
          targetPort: 8282
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-districtpdsmanagement-deployment
  labels:
    app: k8s-districtpdsmanagement
spec:
  selector:
    matchLabels:
      app: k8s-districtpdsmanagement
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-districtpdsmanagement
    spec:
      containers:
        - name: k8s-districtpdsmanagement
          image: gswain3316/districtpdsmanagement:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8282